import { promises as fs } from "node:fs"
import path from "node:path"

import { ESLint } from "eslint"
import { availableParallelism } from "os"
import prettier from "prettier"
import { rimraf } from "rimraf"
import { type Registry, registrySchema } from "shadcn/schema"
import { transformIcons } from "shadcn/utils"
import { Project, ScriptKind } from "ts-morph"

import { getAllBlocks } from "@/lib/blocks"

const REGISTRY_PATH = path.join(process.cwd(), "src/__registry__")
const PUBLIC_REGISTRY_PATH = path.join(process.cwd(), "public/r")

const COMPONENTS_PATH = path.join(process.cwd(), "src/registry/components")
const TRANSFORMED_COMPONENTS_PATH = path.join(
  process.cwd(),
  "src/registry/transformed/components"
)

const CPU_COUNT = availableParallelism()
const COPY_CONCURRENCY = Math.max(4, Math.min(CPU_COUNT, 8))

let prettierConfigPromise: Promise<prettier.Options | null> | null = null

const iconProject = new Project({
  compilerOptions: {},
})

/**
 * Build src/__registry__/registry.autogenerated.json, src/__registry__/index.tsx
 * Thanks @shadcn/ui
 */
export async function buildRegistry(registry: Registry) {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {`
  for (const item of registry.items) {
    if (!Array.isArray(item.files) || !item.files?.length) {
      continue
    }

    const componentFilePath = item.files[0].path
    const componentPath = componentFilePath.startsWith("src/")
      ? componentFilePath.replace("src/", "@/")
      : `@/registry/${componentFilePath}`

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    files: [${item.files.map((file) => {
      const filePath = file.path.startsWith("src/")
        ? file.path
        : `src/registry/${file.path}`
      return `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}",
    }`
    })}],
    component: React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`
  }

  index += `
}`

  // Build /src/__registry__/registry.autogenerated.json
  const registryJSON = JSON.stringify(
    {
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name: "ncdai",
      homepage: "https://chanhdai.com/components",
      items: registry.items
        .filter((item) => item.type !== "registry:example")
        .map((item) => {
          return {
            ...item,
            author: item.author ?? "ncdai <dai@chanhdai.com>",
            files:
              item.files?.map((file) => {
                if (file.path.startsWith("src/")) {
                  return file
                }

                return {
                  ...file,
                  path: `src/registry/${file.path}`,
                }
              }) ?? [],
          }
        }),
    },
    null,
    2
  )

  await rimraf(path.join(REGISTRY_PATH, "registry.autogenerated.json"))
  await fs.writeFile(
    path.join(REGISTRY_PATH, "registry.autogenerated.json"),
    registryJSON,
    "utf8"
  )

  // Build public registry
  await rimraf(path.join(PUBLIC_REGISTRY_PATH, "registry.json"))
  await fs.writeFile(
    path.join(PUBLIC_REGISTRY_PATH, "registry.json"),
    registryJSON,
    "utf8"
  )

  // Build /src/__registry__/index.tsx
  await rimraf(path.join(REGISTRY_PATH, "index.tsx"))
  await fs.writeFile(path.join(REGISTRY_PATH, "index.tsx"), index, "utf8")
}

async function buildBlocksIndex() {
  const blocks = await getAllBlocks(["registry:block"])

  const payload = blocks.map((block) => ({
    name: block.name,
    description: block.description,
    categories: block.categories,
  }))

  // Build /src/__registry__/__blocks__.json
  await rimraf(path.join(REGISTRY_PATH, "__blocks__.json"))
  const blocksJsonPath = path.join(REGISTRY_PATH, "__blocks__.json")
  await fs.writeFile(blocksJsonPath, JSON.stringify(payload, null, 2))
}

async function runWithConcurrency<T, R>(
  items: T[],
  limit: number,
  worker: (item: T, index: number) => Promise<R>
) {
  const results = new Array<R>(items.length)
  let currentIndex = 0

  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      while (true) {
        const index = currentIndex++
        if (index >= items.length) {
          return
        }

        results[index] = await worker(items[index], index)
      }
    })
  )

  return results
}

async function readDirectoryEntries(dirPath: string) {
  try {
    return await fs.readdir(dirPath, { withFileTypes: true })
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return []
    }

    throw error
  }
}

async function readFileIfExists(filePath: string) {
  try {
    return await fs.readFile(filePath, "utf8")
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return null
    }

    throw error
  }
}

async function writeIfChanged(filePath: string, content: string) {
  const existingContent = await readFileIfExists(filePath)
  if (existingContent === content) {
    return false
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true })
  await fs.writeFile(filePath, content)

  return true
}

async function syncDirectory({
  fromDir,
  toDir,
  transformContent,
}: {
  fromDir: string
  toDir: string
  transformContent?: (
    content: string,
    filePath: string,
    targetPath: string
  ) => Promise<string>
}): Promise<string[]> {
  await fs.mkdir(toDir, { recursive: true })

  const [sourceEntries, targetEntries] = await Promise.all([
    fs.readdir(fromDir, { withFileTypes: true }),
    readDirectoryEntries(toDir),
  ])

  const targetEntriesByName = new Map(
    targetEntries.map((entry) => [entry.name, entry])
  )
  const sourceNames = new Set(sourceEntries.map((entry) => entry.name))

  await Promise.all(
    targetEntries.map(async (entry) => {
      if (!sourceNames.has(entry.name)) {
        await rimraf(path.join(toDir, entry.name))
      }
    })
  )

  const changedPaths: string[][] = await runWithConcurrency(
    sourceEntries,
    COPY_CONCURRENCY,
    async (entry) => {
      const sourcePath = path.join(fromDir, entry.name)
      const targetPath = path.join(toDir, entry.name)
      const existingTargetEntry = targetEntriesByName.get(entry.name)

      if (entry.isDirectory()) {
        if (existingTargetEntry && !existingTargetEntry.isDirectory()) {
          await rimraf(targetPath)
        }

        return await syncDirectory({
          fromDir: sourcePath,
          toDir: targetPath,
          transformContent,
        })
      }

      if (existingTargetEntry?.isDirectory()) {
        await rimraf(targetPath)
      }

      let content = await fs.readFile(sourcePath, "utf8")

      if (transformContent) {
        content = await transformContent(content, sourcePath, targetPath)
      }

      return (await writeIfChanged(targetPath, content)) ? [targetPath] : []
    }
  )

  return changedPaths.flat()
}

function rewriteRegistryComponentsImportsToTransformed(content: string) {
  return content.replaceAll(
    `@/registry/components/`,
    `@/registry/transformed/components/`
  )
}

async function applyIconTransform(content: string, filename: string) {
  if (!content.includes("IconPlaceholder")) {
    return content
  }

  const sourceFile = iconProject.createSourceFile(filename, content, {
    scriptKind: ScriptKind.TSX,
    overwrite: true,
  })

  type TransformIconsConfig = Parameters<typeof transformIcons>[0]["config"]
  type IconTransformInput = {
    filename: string
    raw: string
    sourceFile: typeof sourceFile
    config: TransformIconsConfig
  }
  const config = { iconLibrary: "lucide" } as TransformIconsConfig

  await (transformIcons as (opts: IconTransformInput) => Promise<unknown>)({
    filename,
    raw: content,
    sourceFile,
    config,
  })

  return sourceFile.getText()
}

async function formatGeneratedSource(content: string, filePath: string) {
  prettierConfigPromise ??= prettier.resolveConfig(
    path.join(process.cwd(), "package.json")
  )

  const prettierConfig = (await prettierConfigPromise) ?? {}

  return prettier.format(content, {
    ...prettierConfig,
    filepath: filePath,
  })
}

async function copyComponentsToTransformed() {
  await syncDirectory({
    fromDir: COMPONENTS_PATH,
    toDir: TRANSFORMED_COMPONENTS_PATH,
    transformContent: async (content, filePath, targetPath) => {
      let nextContent = rewriteRegistryComponentsImportsToTransformed(content)

      if (filePath.endsWith(".tsx")) {
        nextContent = await applyIconTransform(
          nextContent,
          path.basename(filePath)
        )
      }

      if (targetPath.endsWith(".ts") || targetPath.endsWith(".tsx")) {
        return formatGeneratedSource(nextContent, targetPath)
      }

      return nextContent
    },
  })

  console.log("✅ registry/components → registry/transformed/components")
}

async function formatTransformedComponents() {
  const eslint = new ESLint({ fix: true })

  const results = await eslint.lintFiles(TRANSFORMED_COMPONENTS_PATH)
  await ESLint.outputFixes(results)

  console.log("✅ Formatted transformed components with ESLint")

  return results
}

try {
  console.log("💽 Building registry...")

  const { registry } = await import("@/registry/index")

  const result = registrySchema.safeParse(registry)

  if (!result.success) {
    console.error(result.error)
    process.exit(1)
  }

  await buildRegistry(result.data)

  await buildBlocksIndex()

  await copyComponentsToTransformed()
  await formatTransformedComponents()

  console.log("✅ Done!")
} catch (error) {
  console.error(error)
  process.exit(1)
}
