/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "cn": {
    name: "cn",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/cn.ts",
      type: "registry:lib",
    }],
  },
  "theme-switcher": {
    name: "theme-switcher",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/theme-switcher/theme-switcher.tsx",
      type: "registry:component",
    }],
  },
  "flip-sentences": {
    name: "flip-sentences",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/flip-sentences/flip-sentences.tsx",
      type: "registry:component",
    }],
  },

  "apple-hello-effect": {
    name: "apple-hello-effect",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/apple-hello-effect/apple-hello-effect.tsx",
      type: "registry:component",
    }],
  },
  "wheel-picker": {
    name: "wheel-picker",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/wheel-picker/wheel-picker.tsx",
      type: "registry:component",
    }],
  },
  "spotify-playlist-card": {
    name: "spotify-playlist-card",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/spotify-playlist-card/spotify-playlist-card.tsx",
      type: "registry:component",
    }],
  },
  "apple-hello-effect-demo": {
    name: "apple-hello-effect-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/apple-hello-effect-demo.tsx")),
  },
  "theme-switcher-demo": {
    name: "theme-switcher-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-switcher-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/theme-switcher-demo.tsx")),
  },
  "wheel-picker-demo": {
    name: "wheel-picker-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-demo.tsx")),
  },
  "wheel-picker-form-demo": {
    name: "wheel-picker-form-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-form-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-form-demo.tsx")),
  },

  "spotify-playlist-card-demo": {
    name: "spotify-playlist-card-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/spotify-playlist-card-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/spotify-playlist-card-demo.tsx")),
  },
  "morphing-pill": {
    name: "morphing-pill",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/morphing-pill/morphing-pill.tsx",
      type: "registry:component",
    }],
  },
  "morphing-pill-demo": {
    name: "morphing-pill-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/morphing-pill-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/morphing-pill-demo.tsx")),
  },
}