/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "haptic": {
    name: "haptic",
    description: "Trigger haptic feedback on mobile devices.",
    type: "registry:lib",
    files: [{
      path: "src/registry/lib/haptic/haptic.ts",
      type: "registry:lib",
      target: "@lib/haptic.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/haptic/haptic.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["utilities"],
    meta: undefined,
  },
  "use-sound": {
    name: "use-sound",
    description: "Hook for playing sound effects with volume, playback rate, and interrupt controls.",
    type: "registry:hook",
    files: [{
      path: "src/registry/hooks/sound/use-sound.ts",
      type: "registry:hook",
      target: "@hooks/sound/use-sound.ts",
    },{
      path: "src/registry/lib/sound/sound-engine.ts",
      type: "registry:lib",
      target: "@lib/sound/sound-engine.ts",
    },{
      path: "src/registry/lib/sound/sound-types.ts",
      type: "registry:lib",
      target: "@lib/sound/sound-types.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/hooks/sound/use-sound.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "use-controllable-state": {
    name: "use-controllable-state",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/hooks/use-controllable-state/use-controllable-state.tsx",
      type: "registry:hook",
      target: "@hooks/use-controllable-state.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/hooks/use-controllable-state/use-controllable-state.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-switcher": {
    name: "theme-switcher",
    description: "Toggle between system, light, and dark themes in Next.js apps.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/theme-switcher/theme-switcher.tsx",
      type: "registry:component",
      target: "@components/theme-switcher.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/theme-switcher/theme-switcher.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["controls"],
    meta: undefined,
  },
  "text-flip": {
    name: "text-flip",
    description: "Animated text that cycles through items with a smooth flip transition.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/text-flip/text-flip.tsx",
      type: "registry:component",
      target: "@components/text-flip.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/text-flip/text-flip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "apple-hello-effect": {
    name: "apple-hello-effect",
    description: "SVG writing animation inspired by Apple’s Hello screen.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/apple-hello-effect/apple-hello-effect-english.tsx",
      type: "registry:component",
      target: "@components/apple-hello-effect-english.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/apple-hello-effect/apple-hello-effect-english.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "apple-hello-effect-hindi": {
    name: "apple-hello-effect-hindi",
    description: "SVG writing animation inspired by Apple’s Hello screen.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/apple-hello-effect/apple-hello-effect-hindi.tsx",
      type: "registry:component",
      target: "@components/apple-hello-effect-hindi.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/apple-hello-effect/apple-hello-effect-hindi.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "apple-hello-effect-spanish": {
    name: "apple-hello-effect-spanish",
    description: "SVG writing animation inspired by Apple’s Hello screen.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/apple-hello-effect/apple-hello-effect-spanish.tsx",
      type: "registry:component",
      target: "@components/apple-hello-effect-spanish.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/apple-hello-effect/apple-hello-effect-spanish.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "apple-hello-effect-vietnamese": {
    name: "apple-hello-effect-vietnamese",
    description: "SVG writing animation inspired by Apple’s Hello screen.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/apple-hello-effect/apple-hello-effect-vietnamese.tsx",
      type: "registry:component",
      target: "@components/apple-hello-effect-vietnamese.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/apple-hello-effect/apple-hello-effect-vietnamese.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "wheel-picker": {
    name: "wheel-picker",
    description: "iOS-like wheel picker for React with smooth inertia scrolling and infinite loop support.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/wheel-picker/wheel-picker.tsx",
      type: "registry:component",
      target: "@components/wheel-picker.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/wheel-picker/wheel-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["controls"],
    meta: undefined,
  },
  "chevrons-up-down-icon": {
    name: "chevrons-up-down-icon",
    description: "Animated chevrons icon that morphs between up and down directions.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/chevrons-up-down-icon/chevrons-up-down-icon.tsx",
      type: "registry:component",
      target: "@components/chevrons-up-down-icon.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/chevrons-up-down-icon/chevrons-up-down-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "work-experience": {
    name: "work-experience",
    description: "Display work experiences with role details, company logos, and durations.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/work-experience/work-experience.tsx",
      type: "registry:component",
      target: "@components/work-experience.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/work-experience/work-experience.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "shimmering-text": {
    name: "shimmering-text",
    description: "Smooth, light-sweeping shimmer animation for text.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/shimmering-text/shimmering-text.tsx",
      type: "registry:component",
      target: "@components/shimmering-text.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/shimmering-text/shimmering-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "slide-to-unlock": {
    name: "slide-to-unlock",
    description: "Interactive slider inspired by the classic iPhone “slide to unlock” gesture.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/slide-to-unlock/slide-to-unlock.tsx",
      type: "registry:component",
      target: "@components/slide-to-unlock.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/slide-to-unlock/slide-to-unlock.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["controls"],
    meta: undefined,
  },
  "testimonial": {
    name: "testimonial",
    description: "Display user feedback with author info, avatar, and verified badge.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/testimonial/testimonial.tsx",
      type: "registry:component",
      target: "@components/testimonial.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/testimonial/testimonial.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "github-stars": {
    name: "github-stars",
    description: "Display GitHub repo star count with formatted numbers and full-count tooltip.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/github-stars/github-stars.tsx",
      type: "registry:component",
      target: "@components/github-stars.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/github-stars/github-stars.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "scroll-fade-effect": {
    name: "scroll-fade-effect",
    description: "Fade content edges as you scroll, for both vertical and horizontal layouts.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/scroll-fade-effect/scroll-fade-effect.tsx",
      type: "registry:component",
      target: "@components/scroll-fade-effect.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/scroll-fade-effect/scroll-fade-effect.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "consent-manager": {
    name: "consent-manager",
    description: "Cookie and tracking consent banner for Next.js, built on c15t.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/consent-manager/consent-manager.tsx",
      type: "registry:component",
      target: "@components/consent-manager.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/consent-manager/consent-manager.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["utilities"],
    meta: undefined,
  },
  "copy-button": {
    name: "copy-button",
    description: "Copy text to clipboard with visual, haptic, and audio feedback.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/copy-button/copy-button.tsx",
      type: "registry:component",
      target: "@components/copy-button.tsx",
    },{
      path: "src/hooks/use-copy-to-clipboard.ts",
      type: "registry:hook",
      target: "@hooks/use-copy-to-clipboard.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/copy-button/copy-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["utilities"],
    meta: undefined,
  },
  "code-block-command": {
    name: "code-block-command",
    description: "Display install commands with package manager switcher and copy button.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/code-block-command/code-block-command.tsx",
      type: "registry:component",
      target: "@components/code-block-command.tsx",
    },{
      path: "src/components/base/ui/tabs.tsx",
      type: "registry:component",
      target: "@components/tabs.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/code-block-command/code-block-command.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "testimonial-spotlight": {
    name: "testimonial-spotlight",
    description: "Testimonial card with spotlight effect on hover.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/testimonial-spotlight/testimonial-spotlight.tsx",
      type: "registry:component",
      target: "@components/testimonial-spotlight.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/testimonial-spotlight/testimonial-spotlight.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "glow-card-grid": {
    name: "glow-card-grid",
    description: "Display cards with glowing border and background effects.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/glow-card-grid/glow-card-grid.tsx",
      type: "registry:component",
      target: "@components/glow-card-grid.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/glow-card-grid/glow-card-grid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "middle-truncation": {
    name: "middle-truncation",
    description: "Truncate text in the middle while preserving start and end.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/middle-truncation/middle-truncation.tsx",
      type: "registry:component",
      target: "@components/middle-truncation.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/middle-truncation/middle-truncation.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["typography"],
    meta: undefined,
  },
  "twemoji": {
    name: "twemoji",
    description: "Render Unicode emoji as Twemoji SVG images inline with text.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/twemoji/twemoji.tsx",
      type: "registry:component",
      target: "@components/twemoji.tsx",
    },{
      path: "src/registry/components/twemoji/lib/twemoji-regex.ts",
      type: "registry:lib",
      target: "@lib/twemoji-regex.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/twemoji/twemoji.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["typography"],
    meta: undefined,
  },
  "elastic-slider": {
    name: "elastic-slider",
    description: "Slider with elastic rubber-band drag and magnetic snap feedback.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/elastic-slider/elastic-slider.tsx",
      type: "registry:component",
      target: "@components/elastic-slider.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/elastic-slider/elastic-slider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["controls"],
    meta: undefined,
  },
  "contribution-graph": {
    name: "contribution-graph",
    description: "A GitHub-style contribution graph component that displays activity levels over time.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/contribution-graph/contribution-graph.tsx",
      type: "registry:component",
      target: "@components/contribution-graph.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/contribution-graph/contribution-graph.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "github-contributions": {
    name: "github-contributions",
    description: "Visualize year-long GitHub contribution activity with daily counts, tooltips, and a profile link.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/github-contributions/github-contributions.tsx",
      type: "registry:component",
      target: "@components/github-contributions.tsx",
    },{
      path: "src/registry/components/github-contributions/lib/get-cached-contributions.ts",
      type: "registry:lib",
      target: "@lib/get-cached-contributions.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/github-contributions/github-contributions.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "toc-minimap": {
    name: "toc-minimap",
    description: "Navigate page sections with a compact, hoverable TOC minimap.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/toc-minimap/toc-minimap.tsx",
      type: "registry:component",
      target: "@components/toc-minimap.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/toc-minimap/toc-minimap.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["navigation"],
    meta: undefined,
  },
  "fluid-gradient-text": {
    name: "fluid-gradient-text",
    description: "Render text with a fluid gradient that shifts with pointer movement.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/fluid-gradient-text/fluid-gradient-text.tsx",
      type: "registry:component",
      target: "@components/fluid-gradient-text.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/fluid-gradient-text/fluid-gradient-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "brand-assets-menu": {
    name: "brand-assets-menu",
    description: "Context menu for copying brand SVGs and opening asset links.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/brand-assets-menu/brand-assets-menu.tsx",
      type: "registry:component",
      target: "@components/brand-assets-menu.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/brand-assets-menu/brand-assets-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["menus"],
    meta: undefined,
  },
  "icon-swap": {
    name: "icon-swap",
    description: "Animate icon swaps with scale, blur, and fade transitions.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/icon-swap/icon-swap.tsx",
      type: "registry:component",
      target: "@components/icon-swap.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/icon-swap/icon-swap.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "dot-grid-spotlight": {
    name: "dot-grid-spotlight",
    description: "Interactive dot grid with a cursor-tracking spotlight effect.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/dot-grid-spotlight/dot-grid-spotlight.tsx",
      type: "registry:component",
      target: "@components/dot-grid-spotlight.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/dot-grid-spotlight/dot-grid-spotlight.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "spinning-circular-text": {
    name: "spinning-circular-text",
    description: "Text arranged in a circle with a continuous spinning animation.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/spinning-circular-text/spinning-circular-text.tsx",
      type: "registry:component",
      target: "@components/spinning-circular-text.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/spinning-circular-text/spinning-circular-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "mobius-loop-icon": {
    name: "mobius-loop-icon",
    description: "Animated Mobius loop icon that morphs between circles and infinity shape.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/mobius-loop-icon/mobius-loop-icon.tsx",
      type: "registry:component",
      target: "@components/mobius-loop-icon.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/mobius-loop-icon/mobius-loop-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "logos-carousel": {
    name: "logos-carousel",
    description: "Cycle through logos column by column in a staggered wave.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/logos-carousel/logos-carousel.tsx",
      type: "registry:component",
      target: "@components/logos-carousel.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/logos-carousel/logos-carousel.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "testimonial-2": {
    name: "testimonial-2",
    description: "Display a testimonial quote with author attribution and source link.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/testimonial-2/testimonial-2.tsx",
      type: "registry:component",
      target: "@components/testimonial-2.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/testimonial-2/testimonial-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "line-nav": {
    name: "line-nav",
    description: "Vertical navigation with a line marker that expands on hover and active state.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/line-nav/line-nav.tsx",
      type: "registry:component",
      target: "@components/line-nav.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/line-nav/line-nav.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["navigation"],
    meta: undefined,
  },
  "share-menu": {
    name: "share-menu",
    description: "Share menu to copy a link or post to X, LinkedIn, and the native share sheet.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/share-menu/share-menu.tsx",
      type: "registry:component",
      target: "@components/share-menu.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/share-menu/share-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["menus"],
    meta: undefined,
  },
  "spotlight-logo": {
    name: "spotlight-logo",
    description: "SVG logo with a cursor-tracking gradient highlight and tactile press.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/spotlight-logo/spotlight-logo.tsx",
      type: "registry:component",
      target: "@components/spotlight-logo.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/spotlight-logo/spotlight-logo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "login-01": {
    name: "login-01",
    description: "A simple login form.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/login-01/page.tsx",
      type: "registry:page",
      target: "app/login/page.tsx",
    },{
      path: "src/registry/blocks/login-01/components/login-form.tsx",
      type: "registry:component",
      target: "@components/login-form.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/login-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["application"],
    meta: {"createdAt":"2026-02-22"},
  },
  "hero-01": {
    name: "hero-01",
    description: "A hero section with a golden spiral background.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/hero-01/hero-01.tsx",
      type: "registry:component",
      target: "@components/hero-01.tsx",
    },{
      path: "src/registry/blocks/hero-01/components/hero-01-icons.tsx",
      type: "registry:component",
      target: "@components/hero-01-icons.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/hero-01/hero-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-12"},
  },
  "blog-01": {
    name: "blog-01",
    description: "A blog section with a grid layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/blog-01/blog-01.tsx",
      type: "registry:component",
      target: "@components/blog-01.tsx",
    },{
      path: "src/registry/blocks/blog-01/components/article-item.tsx",
      type: "registry:component",
      target: "@components/article-item.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/blog-01/blog-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-13"},
  },
  "blog-02": {
    name: "blog-02",
    description: "A blog section with a lined grid layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/blog-02/blog-02.tsx",
      type: "registry:component",
      target: "@components/blog-02.tsx",
    },{
      path: "src/registry/blocks/blog-02/components/article-item.tsx",
      type: "registry:component",
      target: "@components/article-item.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/blog-02/blog-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-18"},
  },
  "testimonials-01": {
    name: "testimonials-01",
    description: "A testimonials section with dual marquees.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/testimonials-01/testimonials-01.tsx",
      type: "registry:component",
      target: "@components/testimonials-01.tsx",
    },{
      path: "src/registry/blocks/testimonials-01/components/testimonial-list.tsx",
      type: "registry:component",
      target: "@components/testimonial-list.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/testimonials-01/testimonials-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-20","previewClassName":"container mx-auto min-h-svh content-center-safe"},
  },
  "testimonials-02": {
    name: "testimonials-02",
    description: "A testimonials section with a lined layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/testimonials-02/testimonials-02.tsx",
      type: "registry:component",
      target: "@components/testimonials-02.tsx",
    },{
      path: "src/registry/blocks/testimonials-02/components/testimonial-list.tsx",
      type: "registry:component",
      target: "@components/testimonial-list.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/testimonials-02/testimonials-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-29","previewClassName":"min-h-svh content-center-safe"},
  },
  "experience-01": {
    name: "experience-01",
    description: "A work experience section with a lined layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/experience-01/experience-01.tsx",
      type: "registry:component",
      target: "@components/experience-01.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/experience-01/experience-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-28"},
  },
  "team-01": {
    name: "team-01",
    description: "A team section with glowing cards.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/team-01/team-01.tsx",
      type: "registry:component",
      target: "@components/team-01.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/team-01/team-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-30","previewClassName":"min-h-svh place-items-center-safe content-center-safe"},
  },
  "metrics-01": {
    name: "metrics-01",
    description: "A metrics section with a line chart.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/metrics-01/metrics-01.tsx",
      type: "registry:component",
      target: "@components/metrics-01.tsx",
    },{
      path: "src/registry/blocks/metrics-01/components/metric.tsx",
      type: "registry:component",
      target: "@components/metric.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/metrics-01/metrics-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-05-24","previewClassName":"min-h-svh content-center-safe"},
  },
  "social-links-01": {
    name: "social-links-01",
    description: "A social links section with a lined grid layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/social-links-01/social-links-01.tsx",
      type: "registry:component",
      target: "@components/social-links-01.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/social-links-01/social-links-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-06-16","previewClassName":"min-h-svh content-center-safe"},
  },
  "social-proof-01": {
    name: "social-proof-01",
    description: "A social proof section with a logos carousel.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/social-proof-01/social-proof-01.tsx",
      type: "registry:component",
      target: "@components/social-proof-01.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/social-proof-01/social-proof-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-06-26","previewClassName":"min-h-svh content-center-safe"},
  },
  "text-flip-demo": {
    name: "text-flip-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/text-flip-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/text-flip-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "apple-hello-effect-english-demo": {
    name: "apple-hello-effect-english-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-english-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/apple-hello-effect-english-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "apple-hello-effect-hindi-demo": {
    name: "apple-hello-effect-hindi-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-hindi-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/apple-hello-effect-hindi-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "apple-hello-effect-spanish-demo": {
    name: "apple-hello-effect-spanish-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-spanish-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/apple-hello-effect-spanish-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "apple-hello-effect-vietnamese-demo": {
    name: "apple-hello-effect-vietnamese-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-vietnamese-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/apple-hello-effect-vietnamese-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "apple-hello-effect-languages-demo": {
    name: "apple-hello-effect-languages-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-languages-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/apple-hello-effect-languages-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-switcher-demo": {
    name: "theme-switcher-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-switcher-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/theme-switcher-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "wheel-picker-demo": {
    name: "wheel-picker-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/wheel-picker-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "wheel-picker-form-demo": {
    name: "wheel-picker-form-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-form-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/wheel-picker-form-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "work-experience-demo": {
    name: "work-experience-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/work-experience-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/work-experience-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shimmering-text-demo": {
    name: "shimmering-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmering-text-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/shimmering-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shimmering-text-demo-02": {
    name: "shimmering-text-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmering-text-demo-02.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/shimmering-text-demo-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "slide-to-unlock-demo": {
    name: "slide-to-unlock-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/slide-to-unlock-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "slide-to-unlock-demo-02": {
    name: "slide-to-unlock-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-02.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/slide-to-unlock-demo-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "slide-to-unlock-demo-03": {
    name: "slide-to-unlock-demo-03",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-03.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/slide-to-unlock-demo-03.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "testimonial-demo": {
    name: "testimonial-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonial-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonial-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "testimonials-marquee-demo": {
    name: "testimonials-marquee-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonials-marquee-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonials-marquee-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "testimonials-marquee-demo-02": {
    name: "testimonials-marquee-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonials-marquee-demo-02.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonials-marquee-demo-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-stars-demo": {
    name: "github-stars-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-stars-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-stars-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-fade-effect-demo": {
    name: "scroll-fade-effect-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-fade-effect-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-fade-effect-demo-02": {
    name: "scroll-fade-effect-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-02.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-fade-effect-demo-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-fade-effect-demo-03": {
    name: "scroll-fade-effect-demo-03",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-03.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-fade-effect-demo-03.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-fade-effect-demo-04": {
    name: "scroll-fade-effect-demo-04",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-04.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-fade-effect-demo-04.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "code-block-command-demo": {
    name: "code-block-command-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/code-block-command-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/code-block-command-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "code-block-command-convert": {
    name: "code-block-command-convert",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/code-block-command-convert.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/code-block-command-convert.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "copy-button-demo": {
    name: "copy-button-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/copy-button-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/copy-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "haptic-demo": {
    name: "haptic-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/haptic-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/haptic-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "testimonial-spotlight-demo": {
    name: "testimonial-spotlight-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonial-spotlight-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonial-spotlight-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "glow-card-grid-demo": {
    name: "glow-card-grid-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/glow-card-grid-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/glow-card-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "glow-card-grid-dialkit": {
    name: "glow-card-grid-dialkit",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/glow-card-grid-dialkit.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/glow-card-grid-dialkit.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: {"previewClassName":"min-h-svh place-items-center-safe content-center-safe"},
  },
  "middle-truncation-demo": {
    name: "middle-truncation-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/middle-truncation-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/middle-truncation-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "twemoji-demo": {
    name: "twemoji-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/twemoji-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/twemoji-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-toggle-effect-demo": {
    name: "theme-toggle-effect-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-toggle-effect-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/theme-toggle-effect-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "elastic-slider-demo": {
    name: "elastic-slider-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/elastic-slider-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/elastic-slider-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-demo": {
    name: "github-contributions-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-default-theme": {
    name: "github-contributions-default-theme",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-default-theme.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-default-theme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-winter-theme": {
    name: "github-contributions-winter-theme",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-winter-theme.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-winter-theme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-halloween-theme": {
    name: "github-contributions-halloween-theme",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-halloween-theme.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-halloween-theme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "toc-minimap-demo": {
    name: "toc-minimap-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/toc-minimap-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/toc-minimap-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "fluid-gradient-text-demo": {
    name: "fluid-gradient-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/fluid-gradient-text-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/fluid-gradient-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "fluid-gradient-text-dialkit": {
    name: "fluid-gradient-text-dialkit",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/fluid-gradient-text-dialkit.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/fluid-gradient-text-dialkit.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: {"previewClassName":"min-h-svh place-items-center-safe content-center-safe"},
  },
  "brand-assets-menu-demo": {
    name: "brand-assets-menu-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/brand-assets-menu-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/brand-assets-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "icon-swap-demo": {
    name: "icon-swap-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/icon-swap-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/icon-swap-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dot-grid-spotlight-demo": {
    name: "dot-grid-spotlight-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/dot-grid-spotlight-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/dot-grid-spotlight-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "spinning-circular-text-demo": {
    name: "spinning-circular-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/spinning-circular-text-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/spinning-circular-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "spinning-circular-text-demo-2": {
    name: "spinning-circular-text-demo-2",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/spinning-circular-text-demo-2.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/spinning-circular-text-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mobius-loop-icon-demo": {
    name: "mobius-loop-icon-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/mobius-loop-icon-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/mobius-loop-icon-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chevrons-up-down-icon-demo": {
    name: "chevrons-up-down-icon-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/chevrons-up-down-icon-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/chevrons-up-down-icon-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "logos-carousel-demo": {
    name: "logos-carousel-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/logos-carousel-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/logos-carousel-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: {"previewClassName":"min-h-svh place-items-center-safe content-center-safe"},
  },
  "testimonial-2-demo": {
    name: "testimonial-2-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonial-2-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonial-2-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "line-nav-demo": {
    name: "line-nav-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/line-nav-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/line-nav-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: {"previewClassName":"min-h-svh place-items-center-safe content-center-safe"},
  },
  "share-menu-demo": {
    name: "share-menu-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/share-menu-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/share-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "spotlight-logo-demo": {
    name: "spotlight-logo-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/spotlight-logo-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/spotlight-logo-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}